# -*- coding: utf-8 -*-
"""advertisingt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1adTuRkes6ns1fUmpQDtIn7lX5G03mp7I
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/advertising.csv')
df

df.head()

df.tail()

df.dtypes

df.shape

df.isna().sum()

x=df.iloc[:,:-1]
x

y=df.iloc[:,-1]
y

#regplot
import seaborn as sns
sns.regplot(x=df['TV'],y=y,color='red')

sns.regplot(x=df['Radio'],y=y,color='green')

sns.regplot(x=df['Newspaper'],y=y,color='purple')

#model creation
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred  #machine predicted value(acutal value y test)

y_test

df1=pd.DataFrame({'Acutal':y_test,'pred':y_pred,'difference':y_test-y_pred})
df1

print("slope is")
#zip
list(zip(x,model.coef_))

print("constant is",model.intercept_)

print(model.predict([[310.3,12.3,21.4]]))

#percentage error
from sklearn.metrics import mean_absolute_percentage_error,r2_score
print("MAPE is",mean_absolute_percentage_error(y_test,y_pred))
print("R2 score is",r2_score(y_test,y_pred))



